### PR TITLE
Update Readme.MD

### PR DESCRIPTION
**Pull request by zambo**
Changed the github link to http and fixed a small typo.

### CODE REVIEW

**Comment by lazurey** [comment]
Hi @zambo may I ask why change from `git` to `https`?

**Comment by zambo** [comment]
> Hi @zambo may I ask why change from `git` to `https`?

Hi @lazurey 

Using `git` there's this error by default:
```shell
Cloning into 'content-export-import'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

Using `https` we avoid this error.

**Comment by lazurey** [comment]
Hi @zambo 
Hmm, it's quite weird, this is a public repo and i asked a few people to try clone it using `git`, they don't experience any permission issues.
Would you like to check your ssh key configs again?
If no permission issue, I personally prefer `git`.
Thanks,

**Comment by SalahAdDin** [comment]
It is related to ssh key configs, yes, I got the same fail too, I solved it downloading by `HTTPS`(the easiest way).

**Pull request closed without merging**
